"""Test configuration and fixtures."""

import os
from pathlib import Path

import pytest


def pytest_addoption(parser):
    """Register custom CLI options."""
    parser.addoption(
        "--update-baselines",
        action="store_true",
        default=False,
        help="Regenerate SVG visual regression baselines.",
    )

# Override settings for testing
os.environ.setdefault("UPLOAD_DIR", "/tmp/rescueforge_test/uploads")
os.environ.setdefault("OUTPUT_DIR", "/tmp/rescueforge_test/outputs")

# Works both locally (../../testdata) and in Docker (/app/testdata)
_local_testdata = Path(__file__).parent.parent.parent / "testdata"
_docker_testdata = Path("/app/testdata")
TESTDATA_DIR = _docker_testdata if _docker_testdata.exists() else _local_testdata
SAMPLE_DXF = TESTDATA_DIR / "floorplan_sample.dxf"

# Synthetic test DXFs (generated by testdata/generate_test_dxfs.py)
SYNTHETIC_DXFS = {
    "office_mm": TESTDATA_DIR / "office_simple_mm.dxf",
    "house_m": TESTDATA_DIR / "house_meters.dxf",
    "warehouse_cm": TESTDATA_DIR / "warehouse_cm.dxf",
    "anonymized": TESTDATA_DIR / "anonymized_layers.dxf",
    "multilingual": TESTDATA_DIR / "multilingual_layers.dxf",
}


@pytest.fixture
def sample_dxf_path() -> Path:
    """Path to the sample DXF file."""
    if not SAMPLE_DXF.exists():
        pytest.skip("Sample DXF not found in testdata/")
    return SAMPLE_DXF


@pytest.fixture(params=list(SYNTHETIC_DXFS.keys()))
def synthetic_dxf_path(request) -> Path:
    """Parametrized fixture providing each synthetic DXF file in turn."""
    path = SYNTHETIC_DXFS[request.param]
    if not path.exists():
        pytest.skip(f"Synthetic DXF {request.param} not found — run generate_test_dxfs.py")
    return path


@pytest.fixture
def tmp_output(tmp_path: Path) -> Path:
    """Temporary output directory."""
    out = tmp_path / "output"
    out.mkdir()
    return out
